"""Add RSI

Revision ID: 544ee6e64b6b
Revises: 
Create Date: 2019-08-14 18:17:00.726773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544ee6e64b6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('equityId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equityId'], ['equity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsi')
    # ### end Alembic commands ###
